site_name: PSRAW - PowerShell Reddit API Wrapper Module
site_author: Mark Kraus
repo_url: https://github.com/markekraus/PSRAW/
theme: readthedocs
copyright: "PSRAW is licensed under the <a href='https://github.com/markekraus/PSRAW/raw/master/LICENSE'>MIT license"
pages:
  - Home: index.md
  - PSRAW Project:
    - Contributing to PSRAW: Project/Contributing.md
    - Project News: Project/News.md
  - Change Log: ChangeLog.md
  - Module Help:
    - PSRAW: Module/PSRAW.md
    - about_RedditApiResponse: Module/about_RedditApiResponse.md
    - about_RedditApplication: Module/about_RedditApplication.md
    - about_RedditApplicationType: Module/about_RedditApplicationType.md
    - about_RedditComment: Module/about_RedditComment.md
    - about_RedditDataObject: Module/about_RedditDataObject.md
    - about_RedditDate: Module/about_RedditDate.md
    - about_RedditHeaderSize: Module/about_RedditHeaderSize.md
    - about_RedditLink: Module/about_RedditLink.md
    - about_RedditListing: Module/about_RedditListing.md
    - about_RedditModReport: Module/about_RedditModReport.md
    - about_RedditMore: Module/about_RedditMore.md
    - about_RedditOAuthDuration: Module/about_RedditOAuthDuration.md
    - about_RedditOAuthGrantType: Module/about_RedditOAuthGrantType.md
    - about_RedditOAuthResponse: Module/about_RedditOAuthResponse.md
    - about_RedditOAuthResponseType: Module/about_RedditOAuthResponseType.md
    - about_RedditOAuthScope: Module/about_RedditOAuthScope.md
    - about_RedditOAuthToken: Module/about_RedditOAuthToken.md
    - about_RedditSubmission: Module/about_RedditSubmission.md
    - about_RedditSubreddit: Module/about_RedditSubreddit.md
    - about_RedditThing: Module/about_RedditThing.md
    - about_RedditThingKind: Module/about_RedditThingKind.md
    - about_RedditThingPrefix: Module/about_RedditThingPrefix.md
    - about_RedditUserReport: Module/about_RedditUserReport.md
    - Connect-Reddit: Module/Connect-Reddit.md
    - Export-RedditApplication: Module/Export-RedditApplication.md
    - Export-RedditOAuthToken: Module/Export-RedditOAuthToken.md
    - Get-RedditDefaultOAuthToken: Module/Get-RedditDefaultOAuthToken.md
    - Get-RedditOAuthScope: Module/Get-RedditOAuthScope.md
    - Import-RedditApplication: Module/Import-RedditApplication.md
    - Import-RedditOAuthToken: Module/Import-RedditOAuthToken.md
    - Invoke-RedditRequest: Module/Invoke-RedditRequest.md
    - New-RedditApplication: Module/New-RedditApplication.md
    - Request-RedditOAuthToken: Module/Request-RedditOAuthToken.md
    - Resolve-RedditDataObject: Module/Resolve-RedditDataObject.md
    - Set-RedditDefaultOAuthToken: Module/Set-RedditDefaultOAuthToken.md
    - Update-RedditOAuthToken: Module/Update-RedditOAuthToken.md
  - Private Functions:
    - Get-AuthorizationHeader: PrivateFunctions/Get-AuthorizationHeader.md
    - Get-HttpResponseContentType: PrivateFunctions/Get-HttpResponseContentType.md
    - Request-RedditOAuthTokenClient: PrivateFunctions/Request-RedditOAuthTokenClient.md
    - Request-RedditOAuthTokeninstalled: PrivateFunctions/Request-RedditOAuthTokeninstalled.md
    - Request-RedditOAuthTokenPassword: PrivateFunctions/Request-RedditOAuthTokenPassword.md
    - Wait-RedditApiRateLimit: PrivateFunctions/Wait-RedditApiRateLimit.md
  - Examples:
    - Quicker Quickstart Example for 2.0: Examples/Quickstart.md

